#pragma once
#include <memory>
#include <string>

// Forward declarations (generated by protoc)
namespace codb {
class KVStore;
}

namespace grpc {
class ServerContext;
class Status;
}

#include "kv_store.h"

// Generated gRPC headers (available after cmake build)
// #include "kvstore.grpc.pb.h"

/**
 * KVServiceImpl — bridges gRPC RPC calls to the IKVStore storage layer.
 *
 * This class is intentionally thin:
 *   - Validate input
 *   - Delegate to storage
 *   - Map results to proto response
 *
 * No business logic here. No storage details in the proto layer.
 * This separation allows the storage backend to be swapped freely.
 */

// NOTE: The full implementation requires the generated proto headers.
// This header is a stub — full class definition is in kv_service_impl.cpp
// after the build system generates kvstore.grpc.pb.h
